ALTER TABLE semesters ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'UPCOMING';

UPDATE semesters
SET status = CASE
  WHEN end_date < CURRENT_DATE THEN 'COMPLETED'
  WHEN start_date <= CURRENT_DATE AND end_date >= CURRENT_DATE THEN 'ACTIVE'
  ELSE 'UPCOMING'
END;
