CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE github_repositories (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    github_repo_id bigint,
    owner_login character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    full_name character varying(512) NOT NULL,
    repo_url character varying(512),
    visibility character varying(50),
    default_branch character varying(255),
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT github_repositories_pkey PRIMARY KEY (id)
);

CREATE TABLE github_users (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    github_user_id bigint,
    login character varying(255) NOT NULL,
    display_name character varying(255),
    email character varying(255),
    avatar_url character varying(512),
    user_type character varying(50),
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT github_users_pkey PRIMARY KEY (id)
);

CREATE TABLE jira_projects (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    jira_project_key character varying(50) NOT NULL,
    jira_project_id character varying(100),
    project_name character varying(255) NOT NULL,
    jira_url character varying(512),
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT jira_projects_pkey PRIMARY KEY (id)
);

CREATE TABLE roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    role_name character varying(128) NOT NULL,
    CONSTRAINT roles_pkey PRIMARY KEY (id)
);

CREATE TABLE semesters (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name character varying(50) NOT NULL,
    start_date date,
    end_date date,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT semesters_pkey PRIMARY KEY (id)
);

CREATE TABLE subjects (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    subject_code character varying(50) NOT NULL,
    subject_name character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT subjects_pkey PRIMARY KEY (id)
);

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    full_name character varying(255),
    enabled boolean NOT NULL DEFAULT TRUE,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE github_branches (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    repo_id bigint NOT NULL,
    branch_name character varying(255) NOT NULL,
    is_default boolean NOT NULL DEFAULT FALSE,
    head_commit_sha character varying(64),
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT github_branches_pkey PRIMARY KEY (id),
    CONSTRAINT fk_github_branches_repo FOREIGN KEY (repo_id) REFERENCES github_repositories (id) ON DELETE CASCADE
);

CREATE TABLE github_commits (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    repo_id bigint NOT NULL,
    commit_sha character varying(64) NOT NULL,
    message text,
    author_github_user_id bigint,
    committer_github_user_id bigint,
    committed_at timestamp with time zone,
    additions integer,
    deletions integer,
    changed_files integer,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT github_commits_pkey PRIMARY KEY (id),
    CONSTRAINT fk_github_commits_author FOREIGN KEY (author_github_user_id) REFERENCES github_users (id) ON DELETE SET NULL,
    CONSTRAINT fk_github_commits_committer FOREIGN KEY (committer_github_user_id) REFERENCES github_users (id) ON DELETE SET NULL,
    CONSTRAINT fk_github_commits_repo FOREIGN KEY (repo_id) REFERENCES github_repositories (id) ON DELETE CASCADE
);

CREATE TABLE github_issues (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    repo_id bigint NOT NULL,
    issue_number integer NOT NULL,
    title character varying(512),
    body text,
    state character varying(50),
    author_github_user_id bigint,
    assignee_github_user_id bigint,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone NOT NULL DEFAULT (now()),
    closed_at timestamp with time zone,
    CONSTRAINT github_issues_pkey PRIMARY KEY (id),
    CONSTRAINT fk_github_issues_assignee FOREIGN KEY (assignee_github_user_id) REFERENCES github_users (id) ON DELETE SET NULL,
    CONSTRAINT fk_github_issues_author FOREIGN KEY (author_github_user_id) REFERENCES github_users (id) ON DELETE SET NULL,
    CONSTRAINT fk_github_issues_repo FOREIGN KEY (repo_id) REFERENCES github_repositories (id) ON DELETE CASCADE
);

CREATE TABLE github_pull_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    repo_id bigint NOT NULL,
    pr_number integer NOT NULL,
    title character varying(512),
    body text,
    state character varying(50),
    author_github_user_id bigint,
    source_branch character varying(255),
    target_branch character varying(255),
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone NOT NULL DEFAULT (now()),
    closed_at timestamp with time zone,
    merged_at timestamp with time zone,
    CONSTRAINT github_pull_requests_pkey PRIMARY KEY (id),
    CONSTRAINT fk_github_pull_requests_author FOREIGN KEY (author_github_user_id) REFERENCES github_users (id) ON DELETE SET NULL,
    CONSTRAINT fk_github_pull_requests_repo FOREIGN KEY (repo_id) REFERENCES github_repositories (id) ON DELETE CASCADE
);

CREATE TABLE jira_issues (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    jira_issue_key character varying(50) NOT NULL,
    jira_project_id bigint NOT NULL,
    title character varying(255),
    description text,
    issue_type character varying(50),
    status character varying(50),
    priority character varying(50),
    assignee_jira_account_id character varying(255),
    reporter_jira_account_id character varying(255),
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT jira_issues_pkey PRIMARY KEY (id),
    CONSTRAINT fk_jira_issues_project FOREIGN KEY (jira_project_id) REFERENCES jira_projects (id) ON DELETE CASCADE
);

CREATE TABLE audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    action character varying(100) NOT NULL,
    entity_type character varying(50) NOT NULL,
    entity_id bigint NOT NULL,
    performed_by_user_id bigint,
    timestamp timestamp with time zone NOT NULL DEFAULT (now()),
    ip_address character varying(45),
    user_agent text,
    old_values jsonb,
    new_values jsonb,
    metadata jsonb,
    CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
    CONSTRAINT fk_audit_logs_performed_by FOREIGN KEY (performed_by_user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE TABLE courses (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    semester_id bigint NOT NULL,
    subject_id bigint NOT NULL,
    course_code character varying(50) NOT NULL,
    course_name character varying(255),
    created_by_user_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT courses_pkey PRIMARY KEY (id),
    CONSTRAINT fk_courses_created_by FOREIGN KEY (created_by_user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_courses_semester FOREIGN KEY (semester_id) REFERENCES semesters (id) ON DELETE RESTRICT,
    CONSTRAINT fk_courses_subject FOREIGN KEY (subject_id) REFERENCES subjects (id) ON DELETE RESTRICT
);

CREATE TABLE external_accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    provider character varying(50) NOT NULL,
    external_user_key character varying(255) NOT NULL,
    username character varying(255),
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT external_accounts_pkey PRIMARY KEY (id),
    CONSTRAINT fk_external_accounts_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE lecturers (
    user_id bigint NOT NULL,
    lecturer_code character varying(50) NOT NULL,
    department character varying(255),
    office_email character varying(255),
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT lecturers_pkey PRIMARY KEY (user_id),
    CONSTRAINT fk_lecturers_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE report_exports (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    report_type character varying(50) NOT NULL,
    scope character varying(50) NOT NULL,
    scope_entity_id bigint NOT NULL,
    format character varying(10) NOT NULL,
    status character varying(50) NOT NULL DEFAULT ('PENDING'::character varying),
    file_url character varying(1024),
    file_size_bytes bigint,
    requested_by_user_id bigint NOT NULL,
    requested_at timestamp with time zone NOT NULL DEFAULT (now()),
    completed_at timestamp with time zone,
    error_message text,
    expires_at timestamp with time zone,
    CONSTRAINT report_exports_pkey PRIMARY KEY (id),
    CONSTRAINT fk_report_exports_requested_by FOREIGN KEY (requested_by_user_id) REFERENCES users (id) ON DELETE RESTRICT
);

CREATE TABLE students (
    user_id bigint NOT NULL,
    student_code character varying(50) NOT NULL,
    major character varying(255),
    intake_year integer,
    department character varying(255),
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT students_pkey PRIMARY KEY (user_id),
    CONSTRAINT fk_students_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE user_roles (
    user_id bigint NOT NULL,
    role_id bigint NOT NULL,
    CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE RESTRICT,
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE github_commit_branches (
    branch_id bigint NOT NULL,
    commit_id bigint NOT NULL,
    CONSTRAINT github_commit_branches_pkey PRIMARY KEY (branch_id, commit_id),
    CONSTRAINT fk_github_commit_branches_branch FOREIGN KEY (branch_id) REFERENCES github_branches (id) ON DELETE CASCADE,
    CONSTRAINT fk_github_commit_branches_commit FOREIGN KEY (commit_id) REFERENCES github_commits (id) ON DELETE CASCADE
);

CREATE TABLE github_issue_comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    issue_id bigint NOT NULL,
    author_github_user_id bigint,
    body text,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT github_issue_comments_pkey PRIMARY KEY (id),
    CONSTRAINT fk_github_issue_comments_author FOREIGN KEY (author_github_user_id) REFERENCES github_users (id) ON DELETE SET NULL,
    CONSTRAINT fk_github_issue_comments_issue FOREIGN KEY (issue_id) REFERENCES github_issues (id) ON DELETE CASCADE
);

CREATE TABLE jira_attachments (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    issue_id bigint NOT NULL,
    filename character varying(255) NOT NULL,
    url character varying(1024) NOT NULL,
    uploaded_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT jira_attachments_pkey PRIMARY KEY (id),
    CONSTRAINT fk_jira_attachments_issue FOREIGN KEY (issue_id) REFERENCES jira_issues (id) ON DELETE CASCADE
);

CREATE TABLE jira_issue_comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    issue_id bigint NOT NULL,
    author_jira_account_id character varying(255) NOT NULL,
    body text,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT jira_issue_comments_pkey PRIMARY KEY (id),
    CONSTRAINT fk_jira_issue_comments_issue FOREIGN KEY (issue_id) REFERENCES jira_issues (id) ON DELETE CASCADE
);

CREATE TABLE jira_issue_links (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    parent_issue_id bigint NOT NULL,
    child_issue_id bigint NOT NULL,
    link_type character varying(50) NOT NULL,
    CONSTRAINT jira_issue_links_pkey PRIMARY KEY (id),
    CONSTRAINT fk_jira_issue_links_child FOREIGN KEY (child_issue_id) REFERENCES jira_issues (id) ON DELETE CASCADE,
    CONSTRAINT fk_jira_issue_links_parent FOREIGN KEY (parent_issue_id) REFERENCES jira_issues (id) ON DELETE CASCADE
);

CREATE TABLE jira_worklogs (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    issue_id bigint NOT NULL,
    author_jira_account_id character varying(255) NOT NULL,
    time_spent numeric(6,2) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT jira_worklogs_pkey PRIMARY KEY (id),
    CONSTRAINT fk_jira_worklogs_issue FOREIGN KEY (issue_id) REFERENCES jira_issues (id) ON DELETE CASCADE
);

CREATE TABLE work_links (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    jira_issue_id bigint NOT NULL,
    repo_id bigint NOT NULL,
    link_type character varying(50) NOT NULL,
    commit_id bigint,
    pr_id bigint,
    branch_id bigint,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT work_links_pkey PRIMARY KEY (id),
    CONSTRAINT fk_work_links_branch FOREIGN KEY (branch_id) REFERENCES github_branches (id) ON DELETE CASCADE,
    CONSTRAINT fk_work_links_commit FOREIGN KEY (commit_id) REFERENCES github_commits (id) ON DELETE CASCADE,
    CONSTRAINT fk_work_links_issue FOREIGN KEY (jira_issue_id) REFERENCES jira_issues (id) ON DELETE CASCADE,
    CONSTRAINT fk_work_links_pr FOREIGN KEY (pr_id) REFERENCES github_pull_requests (id) ON DELETE CASCADE,
    CONSTRAINT fk_work_links_repo FOREIGN KEY (repo_id) REFERENCES github_repositories (id) ON DELETE CASCADE
);

CREATE TABLE projects (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    course_id bigint NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    status character varying(50) NOT NULL DEFAULT ('ACTIVE'::character varying),
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT projects_pkey PRIMARY KEY (id),
    CONSTRAINT fk_projects_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE
);

CREATE TABLE course_lecturers (
    course_id bigint NOT NULL,
    lecturer_user_id bigint NOT NULL,
    CONSTRAINT course_lecturers_pkey PRIMARY KEY (course_id, lecturer_user_id),
    CONSTRAINT fk_course_lecturers_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE,
    CONSTRAINT fk_course_lecturers_lecturer FOREIGN KEY (lecturer_user_id) REFERENCES lecturers (user_id) ON DELETE CASCADE
);

CREATE TABLE course_enrollments (
    course_id bigint NOT NULL,
    student_user_id bigint NOT NULL,
    status character varying(50) NOT NULL DEFAULT ('ACTIVE'::character varying),
    enrolled_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT course_enrollments_pkey PRIMARY KEY (course_id, student_user_id),
    CONSTRAINT fk_course_enrollments_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE,
    CONSTRAINT fk_course_enrollments_student FOREIGN KEY (student_user_id) REFERENCES students (user_id) ON DELETE CASCADE
);

CREATE TABLE inactive_alerts (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    alert_type character varying(50) NOT NULL,
    target_entity_type character varying(50) NOT NULL,
    target_entity_id bigint NOT NULL,
    project_id bigint,
    severity character varying(50) NOT NULL DEFAULT ('WARNING'::character varying),
    message text NOT NULL,
    threshold_days integer NOT NULL,
    last_activity_at timestamp with time zone,
    is_resolved boolean NOT NULL DEFAULT FALSE,
    resolved_at timestamp with time zone,
    resolved_by_user_id bigint,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT inactive_alerts_pkey PRIMARY KEY (id),
    CONSTRAINT fk_inactive_alerts_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
    CONSTRAINT fk_inactive_alerts_resolved_by FOREIGN KEY (resolved_by_user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE TABLE project_documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    project_id bigint NOT NULL,
    doc_type character varying(50) NOT NULL,
    version_no integer NOT NULL,
    status character varying(50) NOT NULL DEFAULT ('DRAFT'::character varying),
    file_url character varying(1024) NOT NULL,
    submitted_by_user_id bigint NOT NULL,
    submitted_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT project_documents_pkey PRIMARY KEY (id),
    CONSTRAINT fk_project_documents_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
    CONSTRAINT fk_project_documents_submitted_by FOREIGN KEY (submitted_by_user_id) REFERENCES users (id) ON DELETE RESTRICT
);

CREATE TABLE project_integrations (
    project_id bigint NOT NULL,
    jira_project_id bigint,
    github_repo_id bigint,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT project_integrations_pkey PRIMARY KEY (project_id),
    CONSTRAINT fk_project_integrations_github_repo FOREIGN KEY (github_repo_id) REFERENCES github_repositories (id) ON DELETE SET NULL,
    CONSTRAINT fk_project_integrations_jira_project FOREIGN KEY (jira_project_id) REFERENCES jira_projects (id) ON DELETE SET NULL,
    CONSTRAINT fk_project_integrations_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE
);

CREATE TABLE student_activity_dailies (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    student_user_id bigint NOT NULL,
    project_id bigint NOT NULL,
    activity_date date NOT NULL,
    commits_count integer NOT NULL DEFAULT 0,
    lines_added integer NOT NULL DEFAULT 0,
    lines_deleted integer NOT NULL DEFAULT 0,
    pull_requests_count integer NOT NULL DEFAULT 0,
    code_reviews_count integer NOT NULL DEFAULT 0,
    issues_created integer NOT NULL DEFAULT 0,
    issues_completed integer NOT NULL DEFAULT 0,
    story_points integer NOT NULL DEFAULT 0,
    time_logged_hours numeric(6,2) NOT NULL DEFAULT 0.0,
    comments_count integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT student_activity_dailies_pkey PRIMARY KEY (id),
    CONSTRAINT fk_student_activity_dailies_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
    CONSTRAINT fk_student_activity_dailies_student FOREIGN KEY (student_user_id) REFERENCES students (user_id) ON DELETE CASCADE
);

CREATE TABLE team_members (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    project_id bigint NOT NULL,
    student_user_id bigint NOT NULL,
    team_role character varying(50) NOT NULL DEFAULT ('MEMBER'::character varying),
    responsibility character varying(255),
    participation_status character varying(50) NOT NULL DEFAULT ('ACTIVE'::character varying),
    joined_at timestamp with time zone NOT NULL,
    left_at timestamp with time zone,
    CONSTRAINT team_members_pkey PRIMARY KEY (id),
    CONSTRAINT fk_team_members_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
    CONSTRAINT fk_team_members_student FOREIGN KEY (student_user_id) REFERENCES students (user_id) ON DELETE CASCADE
);

CREATE INDEX idx_audit_logs_entity ON audit_logs (entity_type, entity_id);

CREATE INDEX idx_audit_logs_timestamp ON audit_logs (timestamp);

CREATE INDEX idx_audit_logs_user ON audit_logs (performed_by_user_id);

CREATE INDEX idx_course_enrollments_course_status ON course_enrollments (course_id, status);

CREATE INDEX idx_course_enrollments_student_user_id ON course_enrollments (student_user_id);

CREATE INDEX idx_course_lecturers_lecturer_user_id ON course_lecturers (lecturer_user_id);

CREATE INDEX idx_courses_semester_id ON courses (semester_id);

CREATE INDEX idx_courses_subject_id ON courses (subject_id);

CREATE INDEX "IX_courses_created_by_user_id" ON courses (created_by_user_id);

CREATE UNIQUE INDEX uq_courses_semester_subject_code ON courses (semester_id, subject_id, course_code);

CREATE INDEX idx_external_accounts_user_provider ON external_accounts (user_id, provider);

CREATE UNIQUE INDEX uq_external_accounts_provider_key ON external_accounts (provider, external_user_key);

CREATE UNIQUE INDEX uq_external_accounts_user_provider_key ON external_accounts (user_id, provider, external_user_key);

CREATE UNIQUE INDEX uq_github_branches_repo_branch ON github_branches (repo_id, branch_name);

CREATE INDEX "IX_github_commit_branches_commit_id" ON github_commit_branches (commit_id);

CREATE INDEX idx_github_commits_author ON github_commits (author_github_user_id);

CREATE INDEX idx_github_commits_repo_committed_at ON github_commits (repo_id, committed_at);

CREATE INDEX "IX_github_commits_committer_github_user_id" ON github_commits (committer_github_user_id);

CREATE UNIQUE INDEX uq_github_commits_repo_sha ON github_commits (repo_id, commit_sha);

CREATE INDEX idx_github_issue_comments_issue_created ON github_issue_comments (issue_id, created_at);

CREATE INDEX "IX_github_issue_comments_author_github_user_id" ON github_issue_comments (author_github_user_id);

CREATE INDEX idx_github_issues_repo_state ON github_issues (repo_id, state);

CREATE INDEX "IX_github_issues_assignee_github_user_id" ON github_issues (assignee_github_user_id);

CREATE INDEX "IX_github_issues_author_github_user_id" ON github_issues (author_github_user_id);

CREATE UNIQUE INDEX uq_github_issues_repo_number ON github_issues (repo_id, issue_number);

CREATE INDEX idx_github_pull_requests_author ON github_pull_requests (author_github_user_id);

CREATE INDEX idx_github_pull_requests_repo_state ON github_pull_requests (repo_id, state);

CREATE UNIQUE INDEX uq_github_pull_requests_repo_number ON github_pull_requests (repo_id, pr_number);

CREATE UNIQUE INDEX github_repositories_full_name_key ON github_repositories (full_name);

CREATE UNIQUE INDEX github_repositories_github_repo_id_key ON github_repositories (github_repo_id);

CREATE UNIQUE INDEX uq_github_repositories_owner_name ON github_repositories (owner_login, name);

CREATE UNIQUE INDEX github_users_github_user_id_key ON github_users (github_user_id);

CREATE UNIQUE INDEX github_users_login_key ON github_users (login);

CREATE INDEX idx_inactive_alerts_project ON inactive_alerts (project_id);

CREATE INDEX idx_inactive_alerts_target ON inactive_alerts (target_entity_type, target_entity_id);

CREATE INDEX idx_inactive_alerts_type ON inactive_alerts (alert_type);

CREATE INDEX idx_inactive_alerts_unresolved ON inactive_alerts (is_resolved) WHERE is_resolved = false;

CREATE INDEX "IX_inactive_alerts_resolved_by_user_id" ON inactive_alerts (resolved_by_user_id);

CREATE INDEX idx_jira_attachments_issue_uploaded ON jira_attachments (issue_id, uploaded_at);

CREATE INDEX idx_jira_issue_comments_issue_created ON jira_issue_comments (issue_id, created_at);

CREATE INDEX idx_jira_issue_links_child ON jira_issue_links (child_issue_id);

CREATE INDEX idx_jira_issue_links_parent ON jira_issue_links (parent_issue_id);

CREATE UNIQUE INDEX uq_jira_issue_links_parent_child_type ON jira_issue_links (parent_issue_id, child_issue_id, link_type);

CREATE INDEX idx_jira_issues_project_id ON jira_issues (jira_project_id);

CREATE INDEX idx_jira_issues_project_status ON jira_issues (jira_project_id, status);

CREATE UNIQUE INDEX jira_issues_jira_issue_key_key ON jira_issues (jira_issue_key);

CREATE UNIQUE INDEX jira_projects_jira_project_key_key ON jira_projects (jira_project_key);

CREATE INDEX idx_jira_worklogs_issue_author ON jira_worklogs (issue_id, author_jira_account_id);

CREATE UNIQUE INDEX lecturers_lecturer_code_key ON lecturers (lecturer_code);

CREATE UNIQUE INDEX lecturers_office_email_key ON lecturers (office_email);

CREATE INDEX idx_project_documents_project_doc_type ON project_documents (project_id, doc_type);

CREATE INDEX idx_project_documents_submitted_by ON project_documents (submitted_by_user_id);

CREATE UNIQUE INDEX uq_project_documents_version ON project_documents (project_id, doc_type, version_no);

CREATE UNIQUE INDEX uq_project_integrations_github_repo ON project_integrations (github_repo_id);

CREATE UNIQUE INDEX uq_project_integrations_jira_project ON project_integrations (jira_project_id);

CREATE INDEX idx_projects_course_id ON projects (course_id);

CREATE UNIQUE INDEX uq_projects_course_name ON projects (course_id, name);

CREATE INDEX idx_report_exports_requested_by ON report_exports (requested_by_user_id);

CREATE INDEX idx_report_exports_scope ON report_exports (scope, scope_entity_id);

CREATE INDEX idx_report_exports_status ON report_exports (status);

CREATE UNIQUE INDEX roles_role_name_key ON roles (role_name);

CREATE UNIQUE INDEX semesters_name_key ON semesters (name);

CREATE INDEX idx_student_activity_dailies_date ON student_activity_dailies (activity_date);

CREATE INDEX idx_student_activity_dailies_project ON student_activity_dailies (project_id);

CREATE INDEX idx_student_activity_dailies_student ON student_activity_dailies (student_user_id);

CREATE UNIQUE INDEX uq_student_activity_dailies_student_project_date ON student_activity_dailies (student_user_id, project_id, activity_date);

CREATE UNIQUE INDEX students_student_code_key ON students (student_code);

CREATE UNIQUE INDEX subjects_subject_code_key ON subjects (subject_code);

CREATE INDEX idx_team_members_project_team_role ON team_members (project_id, team_role);

CREATE INDEX idx_team_members_student_user_id ON team_members (student_user_id);

CREATE UNIQUE INDEX uq_team_members_project_student ON team_members (project_id, student_user_id);

CREATE INDEX idx_user_roles_role_id ON user_roles (role_id);

CREATE UNIQUE INDEX users_email_key ON users (email);

CREATE INDEX idx_work_links_issue_id ON work_links (jira_issue_id);

CREATE INDEX idx_work_links_repo_id ON work_links (repo_id);

CREATE INDEX "IX_work_links_branch_id" ON work_links (branch_id);

CREATE INDEX "IX_work_links_commit_id" ON work_links (commit_id);

CREATE INDEX "IX_work_links_pr_id" ON work_links (pr_id);

CREATE UNIQUE INDEX uq_work_links_compound ON work_links (jira_issue_id, link_type, commit_id, pr_id, branch_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260131092937_AddPBLFeaturesTables', '8.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE project_integrations ADD approval_status text NOT NULL DEFAULT '';

ALTER TABLE project_integrations ADD approved_at timestamp with time zone;

ALTER TABLE project_integrations ADD approved_by_user_id bigint;

ALTER TABLE project_integrations ADD approved_byid bigint;

ALTER TABLE project_integrations ADD rejected_reason text;

ALTER TABLE project_integrations ADD submitted_at timestamp with time zone;

ALTER TABLE project_integrations ADD submitted_by_user_id bigint;

ALTER TABLE project_integrations ADD submitted_byid bigint;

CREATE INDEX "IX_project_integrations_approved_byid" ON project_integrations (approved_byid);

CREATE INDEX "IX_project_integrations_submitted_byid" ON project_integrations (submitted_byid);

ALTER TABLE project_integrations ADD CONSTRAINT "FK_project_integrations_users_approved_byid" FOREIGN KEY (approved_byid) REFERENCES users (id);

ALTER TABLE project_integrations ADD CONSTRAINT "FK_project_integrations_users_submitted_byid" FOREIGN KEY (submitted_byid) REFERENCES users (id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260303085059_AddIntegrationApprovalWorkflow', '8.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE users ADD password_reset_token text;

ALTER TABLE users ADD password_reset_token_expires_at timestamp with time zone;

ALTER TABLE team_members ADD contribution_score numeric;

ALTER TABLE courses ADD max_students integer;

ALTER TABLE courses ADD status text NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260305050339_AddMissingFields', '8.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE project_documents ADD feedback text;

ALTER TABLE project_documents ADD reviewed_at timestamp with time zone;

ALTER TABLE project_documents ADD reviewer_user_id bigint;

ALTER TABLE project_documents ADD reviewer_userid bigint;

CREATE TABLE team_invitations (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    project_id bigint NOT NULL,
    invited_by_user_id bigint NOT NULL,
    invited_student_user_id bigint NOT NULL,
    status text NOT NULL,
    message text,
    created_at timestamp with time zone NOT NULL,
    responded_at timestamp with time zone,
    projectid bigint NOT NULL,
    invited_by_userid bigint NOT NULL,
    invited_student_useruser_id bigint NOT NULL,
    CONSTRAINT "PK_team_invitations" PRIMARY KEY (id),
    CONSTRAINT "FK_team_invitations_projects_projectid" FOREIGN KEY (projectid) REFERENCES projects (id) ON DELETE CASCADE,
    CONSTRAINT "FK_team_invitations_students_invited_student_useruser_id" FOREIGN KEY (invited_student_useruser_id) REFERENCES students (user_id) ON DELETE CASCADE,
    CONSTRAINT "FK_team_invitations_users_invited_by_userid" FOREIGN KEY (invited_by_userid) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX "IX_project_documents_reviewer_userid" ON project_documents (reviewer_userid);

CREATE INDEX "IX_team_invitations_invited_by_userid" ON team_invitations (invited_by_userid);

CREATE INDEX "IX_team_invitations_invited_student_useruser_id" ON team_invitations (invited_student_useruser_id);

CREATE INDEX "IX_team_invitations_projectid" ON team_invitations (projectid);

ALTER TABLE project_documents ADD CONSTRAINT "FK_project_documents_users_reviewer_userid" FOREIGN KEY (reviewer_userid) REFERENCES users (id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260305061302_AddInvitationsAndSrs', '8.0.11');

COMMIT;
