// <auto-generated />
using System;
using JiraGithubExport.Shared.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JiraGithubExport.Shared.Migrations
{
    [DbContext(typeof(JiraGithubToolDbContext))]
    [Migration("20260131092937_AddPBLFeaturesTables")]
    partial class AddPBLFeaturesTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JiraGithubExport.Shared.Models.AuditLog", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("entity_id")
                        .HasColumnType("bigint");

                    b.Property<string>("entity_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ip_address")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("metadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("new_values")
                        .HasColumnType("jsonb");

                    b.Property<string>("old_values")
                        .HasColumnType("jsonb");

                    b.Property<long?>("performed_by_user_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("user_agent")
                        .HasColumnType("text");

                    b.HasKey("id")
                        .HasName("audit_logs_pkey");

                    b.HasIndex(new[] { "entity_type", "entity_id" }, "idx_audit_logs_entity");

                    b.HasIndex(new[] { "timestamp" }, "idx_audit_logs_timestamp");

                    b.HasIndex(new[] { "performed_by_user_id" }, "idx_audit_logs_user");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.Course", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("course_code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("course_name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("created_by_user_id")
                        .HasColumnType("bigint");

                    b.Property<long>("semester_id")
                        .HasColumnType("bigint");

                    b.Property<long>("subject_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("id")
                        .HasName("courses_pkey");

                    b.HasIndex("created_by_user_id");

                    b.HasIndex(new[] { "semester_id" }, "idx_courses_semester_id");

                    b.HasIndex(new[] { "subject_id" }, "idx_courses_subject_id");

                    b.HasIndex(new[] { "semester_id", "subject_id", "course_code" }, "uq_courses_semester_subject_code")
                        .IsUnique();

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.CourseEnrollment", b =>
                {
                    b.Property<long>("course_id")
                        .HasColumnType("bigint");

                    b.Property<long>("student_user_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("enrolled_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValueSql("'ACTIVE'::character varying");

                    b.HasKey("course_id", "student_user_id")
                        .HasName("course_enrollments_pkey");

                    b.HasIndex(new[] { "course_id", "status" }, "idx_course_enrollments_course_status");

                    b.HasIndex(new[] { "student_user_id" }, "idx_course_enrollments_student_user_id");

                    b.ToTable("CourseEnrollments");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.ExternalAccount", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("external_user_key")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.Property<string>("username")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("id")
                        .HasName("external_accounts_pkey");

                    b.HasIndex(new[] { "user_id", "provider" }, "idx_external_accounts_user_provider");

                    b.HasIndex(new[] { "provider", "external_user_key" }, "uq_external_accounts_provider_key")
                        .IsUnique();

                    b.HasIndex(new[] { "user_id", "provider", "external_user_key" }, "uq_external_accounts_user_provider_key")
                        .IsUnique();

                    b.ToTable("ExternalAccounts");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.GithubBranch", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("branch_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("head_commit_sha")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("is_default")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<long>("repo_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("id")
                        .HasName("github_branches_pkey");

                    b.HasIndex(new[] { "repo_id", "branch_name" }, "uq_github_branches_repo_branch")
                        .IsUnique();

                    b.ToTable("github_branches");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.GithubCommit", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<int?>("additions")
                        .HasColumnType("integer");

                    b.Property<long?>("author_github_user_id")
                        .HasColumnType("bigint");

                    b.Property<int?>("changed_files")
                        .HasColumnType("integer");

                    b.Property<string>("commit_sha")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("committed_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("committer_github_user_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("deletions")
                        .HasColumnType("integer");

                    b.Property<string>("message")
                        .HasColumnType("text");

                    b.Property<long>("repo_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("id")
                        .HasName("github_commits_pkey");

                    b.HasIndex("committer_github_user_id");

                    b.HasIndex(new[] { "author_github_user_id" }, "idx_github_commits_author");

                    b.HasIndex(new[] { "repo_id", "committed_at" }, "idx_github_commits_repo_committed_at");

                    b.HasIndex(new[] { "repo_id", "commit_sha" }, "uq_github_commits_repo_sha")
                        .IsUnique();

                    b.ToTable("GithubCommits");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.GithubIssue", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long?>("assignee_github_user_id")
                        .HasColumnType("bigint");

                    b.Property<long?>("author_github_user_id")
                        .HasColumnType("bigint");

                    b.Property<string>("body")
                        .HasColumnType("text");

                    b.Property<DateTime?>("closed_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("issue_number")
                        .HasColumnType("integer");

                    b.Property<long>("repo_id")
                        .HasColumnType("bigint");

                    b.Property<string>("state")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("title")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("id")
                        .HasName("github_issues_pkey");

                    b.HasIndex("assignee_github_user_id");

                    b.HasIndex("author_github_user_id");

                    b.HasIndex(new[] { "repo_id", "state" }, "idx_github_issues_repo_state");

                    b.HasIndex(new[] { "repo_id", "issue_number" }, "uq_github_issues_repo_number")
                        .IsUnique();

                    b.ToTable("GithubIssues");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.GithubIssueComment", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long?>("author_github_user_id")
                        .HasColumnType("bigint");

                    b.Property<string>("body")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("issue_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("id")
                        .HasName("github_issue_comments_pkey");

                    b.HasIndex("author_github_user_id");

                    b.HasIndex(new[] { "issue_id", "CreatedAt" }, "idx_github_issue_comments_issue_created");

                    b.ToTable("GithubIssueComments");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.GithubPullRequest", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long?>("author_github_user_id")
                        .HasColumnType("bigint");

                    b.Property<string>("body")
                        .HasColumnType("text");

                    b.Property<DateTime?>("closed_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("merged_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("pr_number")
                        .HasColumnType("integer");

                    b.Property<long>("repo_id")
                        .HasColumnType("bigint");

                    b.Property<string>("source_branch")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("state")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("target_branch")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("title")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("id")
                        .HasName("github_pull_requests_pkey");

                    b.HasIndex(new[] { "author_github_user_id" }, "idx_github_pull_requests_author");

                    b.HasIndex(new[] { "repo_id", "state" }, "idx_github_pull_requests_repo_state");

                    b.HasIndex(new[] { "repo_id", "pr_number" }, "uq_github_pull_requests_repo_number")
                        .IsUnique();

                    b.ToTable("GithubPullRequests");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.GithubRepository", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("default_branch")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<long?>("github_repo_id")
                        .HasColumnType("bigint");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("owner_login")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("repo_url")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("visibility")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("id")
                        .HasName("github_repositories_pkey");

                    b.HasIndex(new[] { "FullName" }, "github_repositories_full_name_key")
                        .IsUnique();

                    b.HasIndex(new[] { "github_repo_id" }, "github_repositories_github_repo_id_key")
                        .IsUnique();

                    b.HasIndex(new[] { "owner_login", "name" }, "uq_github_repositories_owner_name")
                        .IsUnique();

                    b.ToTable("GithubRepositories");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.GithubUser", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("avatar_url")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("display_name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long?>("github_user_id")
                        .HasColumnType("bigint");

                    b.Property<string>("login")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("user_type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("id")
                        .HasName("github_users_pkey");

                    b.HasIndex(new[] { "github_user_id" }, "github_users_github_user_id_key")
                        .IsUnique();

                    b.HasIndex(new[] { "login" }, "github_users_login_key")
                        .IsUnique();

                    b.ToTable("GithubUsers");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.InactiveAlert", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("alert_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("is_resolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("last_activity_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("project_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("resolved_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("resolved_by_user_id")
                        .HasColumnType("bigint");

                    b.Property<string>("severity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValueSql("'WARNING'::character varying");

                    b.Property<long>("target_entity_id")
                        .HasColumnType("bigint");

                    b.Property<string>("target_entity_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("threshold_days")
                        .HasColumnType("integer");

                    b.HasKey("id")
                        .HasName("inactive_alerts_pkey");

                    b.HasIndex("resolved_by_user_id");

                    b.HasIndex(new[] { "project_id" }, "idx_inactive_alerts_project");

                    b.HasIndex(new[] { "target_entity_type", "target_entity_id" }, "idx_inactive_alerts_target");

                    b.HasIndex(new[] { "alert_type" }, "idx_inactive_alerts_type");

                    b.HasIndex(new[] { "is_resolved" }, "idx_inactive_alerts_unresolved")
                        .HasFilter("IsResolved = false");

                    b.ToTable("InactiveAlerts");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.JiraAttachment", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("filename")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("issue_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("uploaded_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("id")
                        .HasName("jira_attachments_pkey");

                    b.HasIndex(new[] { "issue_id", "uploaded_at" }, "idx_jira_attachments_issue_uploaded");

                    b.ToTable("JiraAttachments");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.JiraIssue", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("assignee_jira_account_id")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("issue_type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("jira_issue_key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("jira_project_id")
                        .HasColumnType("bigint");

                    b.Property<string>("priority")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("reporter_jira_account_id")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("id")
                        .HasName("jira_issues_pkey");

                    b.HasIndex(new[] { "jira_project_id" }, "idx_jira_issues_project_id");

                    b.HasIndex(new[] { "jira_project_id", "status" }, "idx_jira_issues_project_status");

                    b.HasIndex(new[] { "jira_issue_key" }, "jira_issues_jira_issue_key_key")
                        .IsUnique();

                    b.ToTable("JiraIssues");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.JiraIssueComment", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("author_jira_account_id")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("body")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("issue_id")
                        .HasColumnType("bigint");

                    b.HasKey("id")
                        .HasName("jira_issue_comments_pkey");

                    b.HasIndex(new[] { "issue_id", "CreatedAt" }, "idx_jira_issue_comments_issue_created");

                    b.ToTable("JiraIssueComments");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.JiraIssueLink", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long>("child_issue_id")
                        .HasColumnType("bigint");

                    b.Property<string>("link_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("parent_issue_id")
                        .HasColumnType("bigint");

                    b.HasKey("id")
                        .HasName("jira_issue_links_pkey");

                    b.HasIndex(new[] { "child_issue_id" }, "idx_jira_issue_links_child");

                    b.HasIndex(new[] { "parent_issue_id" }, "idx_jira_issue_links_parent");

                    b.HasIndex(new[] { "parent_issue_id", "child_issue_id", "link_type" }, "uq_jira_issue_links_parent_child_type")
                        .IsUnique();

                    b.ToTable("JiraIssueLinks");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.JiraProject", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("jira_project_id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("jira_project_key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("jira_url")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("project_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("id")
                        .HasName("jira_projects_pkey");

                    b.HasIndex(new[] { "jira_project_key" }, "jira_projects_jira_project_key_key")
                        .IsUnique();

                    b.ToTable("JiraProjects");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.JiraWorklog", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("author_jira_account_id")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("issue_id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("time_spent")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.HasKey("id")
                        .HasName("jira_worklogs_pkey");

                    b.HasIndex(new[] { "issue_id", "author_jira_account_id" }, "idx_jira_worklogs_issue_author");

                    b.ToTable("JiraWorklogs");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.Lecturer", b =>
                {
                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("department")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("lecturer_code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("office_email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("user_id")
                        .HasName("lecturers_pkey");

                    b.HasIndex(new[] { "lecturer_code" }, "lecturers_lecturer_code_key")
                        .IsUnique();

                    b.HasIndex(new[] { "office_email" }, "lecturers_office_email_key")
                        .IsUnique();

                    b.ToTable("Lecturers");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.Project", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long>("course_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValueSql("'ACTIVE'::character varying");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("id")
                        .HasName("projects_pkey");

                    b.HasIndex(new[] { "course_id" }, "idx_projects_course_id");

                    b.HasIndex(new[] { "course_id", "name" }, "uq_projects_course_name")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.ProjectDocument", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("doc_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("file_url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<long>("project_id")
                        .HasColumnType("bigint");

                    b.Property<string>("status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValueSql("'DRAFT'::character varying");

                    b.Property<DateTime>("submitted_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("submitted_by_user_id")
                        .HasColumnType("bigint");

                    b.Property<int>("version_no")
                        .HasColumnType("integer");

                    b.HasKey("id")
                        .HasName("project_documents_pkey");

                    b.HasIndex(new[] { "project_id", "doc_type" }, "idx_project_documents_project_doc_type");

                    b.HasIndex(new[] { "submitted_by_user_id" }, "idx_project_documents_submitted_by");

                    b.HasIndex(new[] { "project_id", "doc_type", "version_no" }, "uq_project_documents_version")
                        .IsUnique();

                    b.ToTable("ProjectDocuments");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.ProjectIntegration", b =>
                {
                    b.Property<long>("project_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("github_repo_id")
                        .HasColumnType("bigint");

                    b.Property<long?>("jira_project_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("project_id")
                        .HasName("project_integrations_pkey");

                    b.HasIndex(new[] { "github_repo_id" }, "uq_project_integrations_github_repo")
                        .IsUnique();

                    b.HasIndex(new[] { "jira_project_id" }, "uq_project_integrations_jira_project")
                        .IsUnique();

                    b.ToTable("ProjectIntegrations");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.ReportExport", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<DateTime?>("completed_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("error_message")
                        .HasColumnType("text");

                    b.Property<DateTime?>("expires_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("file_size_bytes")
                        .HasColumnType("bigint");

                    b.Property<string>("file_url")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("format")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("report_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("requested_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("requested_by_user_id")
                        .HasColumnType("bigint");

                    b.Property<string>("scope")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("scope_entity_id")
                        .HasColumnType("bigint");

                    b.Property<string>("status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValueSql("'PENDING'::character varying");

                    b.HasKey("id")
                        .HasName("report_exports_pkey");

                    b.HasIndex(new[] { "requested_by_user_id" }, "idx_report_exports_requested_by");

                    b.HasIndex(new[] { "scope", "scope_entity_id" }, "idx_report_exports_scope");

                    b.HasIndex(new[] { "status" }, "idx_report_exports_status");

                    b.ToTable("ReportExports");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.Role", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("role_name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("id")
                        .HasName("roles_pkey");

                    b.HasIndex(new[] { "role_name" }, "roles_role_name_key")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.Semester", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("end_date")
                        .HasColumnType("date");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly?>("start_date")
                        .HasColumnType("date");

                    b.HasKey("id")
                        .HasName("semesters_pkey");

                    b.HasIndex(new[] { "name" }, "semesters_name_key")
                        .IsUnique();

                    b.ToTable("Semesters");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.Student", b =>
                {
                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("department")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("intake_year")
                        .HasColumnType("integer");

                    b.Property<string>("major")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("student_code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("user_id")
                        .HasName("students_pkey");

                    b.HasIndex(new[] { "student_code" }, "students_student_code_key")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.StudentActivityDaily", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<DateOnly>("activity_date")
                        .HasColumnType("date");

                    b.Property<int>("code_reviews_count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("comments_count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("commits_count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("issues_completed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("issues_created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("lines_added")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("lines_deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<long>("project_id")
                        .HasColumnType("bigint");

                    b.Property<int>("pull_requests_count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("story_points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<long>("student_user_id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("time_logged_hours")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("id")
                        .HasName("student_activity_dailies_pkey");

                    b.HasIndex(new[] { "activity_date" }, "idx_student_activity_dailies_date");

                    b.HasIndex(new[] { "project_id" }, "idx_student_activity_dailies_project");

                    b.HasIndex(new[] { "student_user_id" }, "idx_student_activity_dailies_student");

                    b.HasIndex(new[] { "student_user_id", "project_id", "activity_date" }, "uq_student_activity_dailies_student_project_date")
                        .IsUnique();

                    b.ToTable("StudentActivityDailies");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.Subject", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("subject_code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("subject_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("id")
                        .HasName("subjects_pkey");

                    b.HasIndex(new[] { "subject_code" }, "subjects_subject_code_key")
                        .IsUnique();

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.TeamMember", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<DateTime>("joined_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("left_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("participation_status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValueSql("'ACTIVE'::character varying");

                    b.Property<long>("project_id")
                        .HasColumnType("bigint");

                    b.Property<string>("responsibility")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("student_user_id")
                        .HasColumnType("bigint");

                    b.Property<string>("team_role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValueSql("'MEMBER'::character varying");

                    b.HasKey("id")
                        .HasName("team_members_pkey");

                    b.HasIndex(new[] { "project_id", "team_role" }, "idx_team_members_project_team_role");

                    b.HasIndex(new[] { "student_user_id" }, "idx_team_members_student_user_id");

                    b.HasIndex(new[] { "project_id", "student_user_id" }, "uq_team_members_project_student")
                        .IsUnique();

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.User", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("id")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.WorkLink", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long?>("branch_id")
                        .HasColumnType("bigint");

                    b.Property<long?>("commit_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("jira_issue_id")
                        .HasColumnType("bigint");

                    b.Property<string>("link_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long?>("pr_id")
                        .HasColumnType("bigint");

                    b.Property<long>("repo_id")
                        .HasColumnType("bigint");

                    b.HasKey("id")
                        .HasName("work_links_pkey");

                    b.HasIndex("branch_id");

                    b.HasIndex("commit_id");

                    b.HasIndex("pr_id");

                    b.HasIndex(new[] { "jira_issue_id" }, "idx_work_links_issue_id");

                    b.HasIndex(new[] { "repo_id" }, "idx_work_links_repo_id");

                    b.HasIndex(new[] { "jira_issue_id", "link_type", "commit_id", "pr_id", "branch_id" }, "uq_work_links_compound")
                        .IsUnique();

                    b.ToTable("WorkLinks");
                });

            modelBuilder.Entity("course_lecturer", b =>
                {
                    b.Property<long>("course_id")
                        .HasColumnType("bigint");

                    b.Property<long>("lecturer_user_id")
                        .HasColumnType("bigint");

                    b.HasKey("course_id", "lecturer_user_id")
                        .HasName("course_lecturers_pkey");

                    b.HasIndex(new[] { "lecturer_user_id" }, "idx_course_lecturers_lecturer_user_id");

                    b.ToTable("course_lecturers", (string)null);
                });

            modelBuilder.Entity("github_commit_branch", b =>
                {
                    b.Property<long>("branch_id")
                        .HasColumnType("bigint");

                    b.Property<long>("commit_id")
                        .HasColumnType("bigint");

                    b.HasKey("branch_id", "commit_id")
                        .HasName("github_commit_branches_pkey");

                    b.HasIndex("commit_id");

                    b.ToTable("github_commit_branches", (string)null);
                });

            modelBuilder.Entity("user_role", b =>
                {
                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.Property<long>("role_id")
                        .HasColumnType("bigint");

                    b.HasKey("user_id", "role_id")
                        .HasName("user_roles_pkey");

                    b.HasIndex(new[] { "role_id" }, "idx_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.AuditLog", b =>
                {
                    b.HasOne("JiraGithubExport.Shared.Models.User", "performed_by_user")
                        .WithMany()
                        .HasForeignKey("performed_by_user_id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_audit_logs_performed_by");

                    b.Navigation("performed_by_user");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.Course", b =>
                {
                    b.HasOne("JiraGithubExport.Shared.Models.User", "created_by_user")
                        .WithMany("Courses")
                        .HasForeignKey("created_by_user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_courses_created_by");

                    b.HasOne("JiraGithubExport.Shared.Models.Semester", "Semester")
                        .WithMany("Courses")
                        .HasForeignKey("semester_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_courses_semester");

                    b.HasOne("JiraGithubExport.Shared.Models.Subject", "Subject")
                        .WithMany("Courses")
                        .HasForeignKey("subject_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_courses_subject");

                    b.Navigation("created_by_user");

                    b.Navigation("Semester");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.CourseEnrollment", b =>
                {
                    b.HasOne("JiraGithubExport.Shared.Models.Course", "Course")
                        .WithMany("CourseEnrollments")
                        .HasForeignKey("course_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_course_enrollments_course");

                    b.HasOne("JiraGithubExport.Shared.Models.Student", "student_user")
                        .WithMany("CourseEnrollments")
                        .HasForeignKey("student_user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_course_enrollments_student");

                    b.Navigation("Course");

                    b.Navigation("student_user");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.ExternalAccount", b =>
                {
                    b.HasOne("JiraGithubExport.Shared.Models.User", "User")
                        .WithMany("ExternalAccounts")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_external_accounts_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.GithubBranch", b =>
                {
                    b.HasOne("JiraGithubExport.Shared.Models.GithubRepository", "repo")
                        .WithMany("github_branches")
                        .HasForeignKey("repo_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_github_branches_repo");

                    b.Navigation("repo");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.GithubCommit", b =>
                {
                    b.HasOne("JiraGithubExport.Shared.Models.GithubUser", "author_github_user")
                        .WithMany("github_commitauthor_github_users")
                        .HasForeignKey("author_github_user_id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_github_commits_author");

                    b.HasOne("JiraGithubExport.Shared.Models.GithubUser", "committer_github_user")
                        .WithMany("github_commitcommitter_github_users")
                        .HasForeignKey("committer_github_user_id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_github_commits_committer");

                    b.HasOne("JiraGithubExport.Shared.Models.GithubRepository", "repo")
                        .WithMany("GithubCommits")
                        .HasForeignKey("repo_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_github_commits_repo");

                    b.Navigation("author_github_user");

                    b.Navigation("committer_github_user");

                    b.Navigation("repo");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.GithubIssue", b =>
                {
                    b.HasOne("JiraGithubExport.Shared.Models.GithubUser", "assignee_github_user")
                        .WithMany("github_issueassignee_github_users")
                        .HasForeignKey("assignee_github_user_id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_github_issues_assignee");

                    b.HasOne("JiraGithubExport.Shared.Models.GithubUser", "author_github_user")
                        .WithMany("github_issueauthor_github_users")
                        .HasForeignKey("author_github_user_id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_github_issues_author");

                    b.HasOne("JiraGithubExport.Shared.Models.GithubRepository", "repo")
                        .WithMany("GithubIssues")
                        .HasForeignKey("repo_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_github_issues_repo");

                    b.Navigation("assignee_github_user");

                    b.Navigation("author_github_user");

                    b.Navigation("repo");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.GithubIssueComment", b =>
                {
                    b.HasOne("JiraGithubExport.Shared.Models.GithubUser", "author_github_user")
                        .WithMany("GithubIssueComments")
                        .HasForeignKey("author_github_user_id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_github_issue_comments_author");

                    b.HasOne("JiraGithubExport.Shared.Models.GithubIssue", "issue")
                        .WithMany("GithubIssueComments")
                        .HasForeignKey("issue_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_github_issue_comments_issue");

                    b.Navigation("author_github_user");

                    b.Navigation("issue");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.GithubPullRequest", b =>
                {
                    b.HasOne("JiraGithubExport.Shared.Models.GithubUser", "author_github_user")
                        .WithMany("GithubPullRequests")
                        .HasForeignKey("author_github_user_id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_github_pull_requests_author");

                    b.HasOne("JiraGithubExport.Shared.Models.GithubRepository", "repo")
                        .WithMany("GithubPullRequests")
                        .HasForeignKey("repo_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_github_pull_requests_repo");

                    b.Navigation("author_github_user");

                    b.Navigation("repo");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.InactiveAlert", b =>
                {
                    b.HasOne("JiraGithubExport.Shared.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("project_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_inactive_alerts_project");

                    b.HasOne("JiraGithubExport.Shared.Models.User", "resolved_by_user")
                        .WithMany()
                        .HasForeignKey("resolved_by_user_id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_inactive_alerts_resolved_by");

                    b.Navigation("Project");

                    b.Navigation("resolved_by_user");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.JiraAttachment", b =>
                {
                    b.HasOne("JiraGithubExport.Shared.Models.JiraIssue", "issue")
                        .WithMany("JiraAttachments")
                        .HasForeignKey("issue_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_jira_attachments_issue");

                    b.Navigation("issue");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.JiraIssue", b =>
                {
                    b.HasOne("JiraGithubExport.Shared.Models.JiraProject", "JiraProject")
                        .WithMany("JiraIssues")
                        .HasForeignKey("jira_project_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_jira_issues_project");

                    b.Navigation("JiraProject");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.JiraIssueComment", b =>
                {
                    b.HasOne("JiraGithubExport.Shared.Models.JiraIssue", "issue")
                        .WithMany("JiraIssueComments")
                        .HasForeignKey("issue_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_jira_issue_comments_issue");

                    b.Navigation("issue");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.JiraIssueLink", b =>
                {
                    b.HasOne("JiraGithubExport.Shared.Models.JiraIssue", "child_issue")
                        .WithMany("jira_issue_linkchild_issues")
                        .HasForeignKey("child_issue_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_jira_issue_links_child");

                    b.HasOne("JiraGithubExport.Shared.Models.JiraIssue", "parent_issue")
                        .WithMany("jira_issue_linkparent_issues")
                        .HasForeignKey("parent_issue_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_jira_issue_links_parent");

                    b.Navigation("child_issue");

                    b.Navigation("parent_issue");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.JiraWorklog", b =>
                {
                    b.HasOne("JiraGithubExport.Shared.Models.JiraIssue", "issue")
                        .WithMany("JiraWorklogs")
                        .HasForeignKey("issue_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_jira_worklogs_issue");

                    b.Navigation("issue");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.Lecturer", b =>
                {
                    b.HasOne("JiraGithubExport.Shared.Models.User", "User")
                        .WithOne("Lecturer")
                        .HasForeignKey("JiraGithubExport.Shared.Models.Lecturer", "user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lecturers_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.Project", b =>
                {
                    b.HasOne("JiraGithubExport.Shared.Models.Course", "Course")
                        .WithMany("Projects")
                        .HasForeignKey("course_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_projects_course");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.ProjectDocument", b =>
                {
                    b.HasOne("JiraGithubExport.Shared.Models.Project", "Project")
                        .WithMany("ProjectDocuments")
                        .HasForeignKey("project_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_documents_project");

                    b.HasOne("JiraGithubExport.Shared.Models.User", "submitted_by_user")
                        .WithMany("ProjectDocuments")
                        .HasForeignKey("submitted_by_user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_documents_submitted_by");

                    b.Navigation("Project");

                    b.Navigation("submitted_by_user");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.ProjectIntegration", b =>
                {
                    b.HasOne("JiraGithubExport.Shared.Models.GithubRepository", "github_repo")
                        .WithOne("ProjectIntegration")
                        .HasForeignKey("JiraGithubExport.Shared.Models.ProjectIntegration", "github_repo_id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_project_integrations_github_repo");

                    b.HasOne("JiraGithubExport.Shared.Models.JiraProject", "JiraProject")
                        .WithOne("ProjectIntegration")
                        .HasForeignKey("JiraGithubExport.Shared.Models.ProjectIntegration", "jira_project_id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_project_integrations_jira_project");

                    b.HasOne("JiraGithubExport.Shared.Models.Project", "Project")
                        .WithOne("ProjectIntegration")
                        .HasForeignKey("JiraGithubExport.Shared.Models.ProjectIntegration", "project_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_integrations_project");

                    b.Navigation("github_repo");

                    b.Navigation("JiraProject");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.ReportExport", b =>
                {
                    b.HasOne("JiraGithubExport.Shared.Models.User", "requested_by_user")
                        .WithMany()
                        .HasForeignKey("requested_by_user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_report_exports_requested_by");

                    b.Navigation("requested_by_user");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.Student", b =>
                {
                    b.HasOne("JiraGithubExport.Shared.Models.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("JiraGithubExport.Shared.Models.Student", "user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_students_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.StudentActivityDaily", b =>
                {
                    b.HasOne("JiraGithubExport.Shared.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("project_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_activity_dailies_project");

                    b.HasOne("JiraGithubExport.Shared.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("student_user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_activity_dailies_student");

                    b.Navigation("Project");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.TeamMember", b =>
                {
                    b.HasOne("JiraGithubExport.Shared.Models.Project", "Project")
                        .WithMany("TeamMembers")
                        .HasForeignKey("project_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_team_members_project");

                    b.HasOne("JiraGithubExport.Shared.Models.Student", "student_user")
                        .WithMany("TeamMembers")
                        .HasForeignKey("student_user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_team_members_student");

                    b.Navigation("Project");

                    b.Navigation("student_user");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.WorkLink", b =>
                {
                    b.HasOne("JiraGithubExport.Shared.Models.GithubBranch", "branch")
                        .WithMany("WorkLinks")
                        .HasForeignKey("branch_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_work_links_branch");

                    b.HasOne("JiraGithubExport.Shared.Models.GithubCommit", "commit")
                        .WithMany("WorkLinks")
                        .HasForeignKey("commit_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_work_links_commit");

                    b.HasOne("JiraGithubExport.Shared.Models.JiraIssue", "JiraIssue")
                        .WithMany("WorkLinks")
                        .HasForeignKey("jira_issue_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_work_links_issue");

                    b.HasOne("JiraGithubExport.Shared.Models.GithubPullRequest", "pr")
                        .WithMany("WorkLinks")
                        .HasForeignKey("pr_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_work_links_pr");

                    b.HasOne("JiraGithubExport.Shared.Models.GithubRepository", "repo")
                        .WithMany("WorkLinks")
                        .HasForeignKey("repo_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_work_links_repo");

                    b.Navigation("branch");

                    b.Navigation("commit");

                    b.Navigation("JiraIssue");

                    b.Navigation("pr");

                    b.Navigation("repo");
                });

            modelBuilder.Entity("course_lecturer", b =>
                {
                    b.HasOne("JiraGithubExport.Shared.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("course_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_course_lecturers_course");

                    b.HasOne("JiraGithubExport.Shared.Models.Lecturer", null)
                        .WithMany()
                        .HasForeignKey("lecturer_user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_course_lecturers_lecturer");
                });

            modelBuilder.Entity("github_commit_branch", b =>
                {
                    b.HasOne("JiraGithubExport.Shared.Models.GithubBranch", null)
                        .WithMany()
                        .HasForeignKey("branch_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_github_commit_branches_branch");

                    b.HasOne("JiraGithubExport.Shared.Models.GithubCommit", null)
                        .WithMany()
                        .HasForeignKey("commit_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_github_commit_branches_commit");
                });

            modelBuilder.Entity("user_role", b =>
                {
                    b.HasOne("JiraGithubExport.Shared.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_role");

                    b.HasOne("JiraGithubExport.Shared.Models.User", null)
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_user");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.Course", b =>
                {
                    b.Navigation("CourseEnrollments");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.GithubBranch", b =>
                {
                    b.Navigation("WorkLinks");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.GithubCommit", b =>
                {
                    b.Navigation("WorkLinks");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.GithubIssue", b =>
                {
                    b.Navigation("GithubIssueComments");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.GithubPullRequest", b =>
                {
                    b.Navigation("WorkLinks");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.GithubRepository", b =>
                {
                    b.Navigation("github_branches");

                    b.Navigation("GithubCommits");

                    b.Navigation("GithubIssues");

                    b.Navigation("GithubPullRequests");

                    b.Navigation("ProjectIntegration");

                    b.Navigation("WorkLinks");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.GithubUser", b =>
                {
                    b.Navigation("github_commitauthor_github_users");

                    b.Navigation("github_commitcommitter_github_users");

                    b.Navigation("GithubIssueComments");

                    b.Navigation("github_issueassignee_github_users");

                    b.Navigation("github_issueauthor_github_users");

                    b.Navigation("GithubPullRequests");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.JiraIssue", b =>
                {
                    b.Navigation("JiraAttachments");

                    b.Navigation("JiraIssueComments");

                    b.Navigation("jira_issue_linkchild_issues");

                    b.Navigation("jira_issue_linkparent_issues");

                    b.Navigation("JiraWorklogs");

                    b.Navigation("WorkLinks");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.JiraProject", b =>
                {
                    b.Navigation("JiraIssues");

                    b.Navigation("ProjectIntegration");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.Project", b =>
                {
                    b.Navigation("ProjectDocuments");

                    b.Navigation("ProjectIntegration");

                    b.Navigation("TeamMembers");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.Semester", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.Student", b =>
                {
                    b.Navigation("CourseEnrollments");

                    b.Navigation("TeamMembers");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.Subject", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("JiraGithubExport.Shared.Models.User", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("ExternalAccounts");

                    b.Navigation("Lecturer");

                    b.Navigation("ProjectDocuments");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
